version: '3.5'

services:
  web:
    container_name: web
    restart: always
    build:
      context: ./docker/nginx      
    ports:
      - 250:80
    volumes:
      - ./:/appdata/www/public      
      # si hubiera una capeta llamda public con todos los codigos dentro
      #- ./public:/appdata/www/public      
    depends_on:
      - platform-be
    networks:
      - platform-network

  platform-be:
    container_name: platform-be
    build:
      context: docker/php    
    volumes:
      #ruta de acceso al codigo desde fpm, en caso contrario muestra mensaje de
      # "file not found" en el navegador
      - ./:/appdata/www/public      
      #- ./public:/appdata/www/public                        
    depends_on:
      - platform-db
    networks:
      - platform-network

  platform-db:
    container_name: platform-db
    restart: always
    image: mysql:8.0    
    #image: mysql:5.7
    ports:
      - 3600:3306
    environment:
      #creamos la base de datos
      MYSQL_DATABASE: db_sistema
      MYSQL_USER: javier
      MYSQL_PASSWORD: 123
      # usuario "root" exite por defecto
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - platform-db-data:/var/lib/mysql
    networks:
      - platform-network

volumes:
  platform-db-data:

networks:
  platform-network:
    external: true